### ISSUE TITLE
SAVI and other indices require reflectance values

### ISSUE THREAD

**Issue by philippgaertner** [awesome-spectral-indices/spectral#1]
Many spectral indices (e.g. SAVI) in your list require reflectance values and don't work with the default values. Please multiply the pixel values by 'scale' (0.0001) when you use Sentinel-2 or Landsat5/7/8 SR products.

**Comment by davemlz** [comment]
Thank you, @philippgaertner! I'll work on it! :)

**Comment by davemlz** [comment]
Hi, @philippgaertner!

I've added new methods to scale and offset images (if required) before computing spectral indices. I've also updated the examples and the documentation. If you could check it and test it, I would really appreciate it! :)

And any other suggestion is welcome!
