### ISSUE TITLE
Scale factors of Landsat 8 Collection 2

### ISSUE THREAD

**Issue by iagomoliv** [awesome-spectral-indices/spectral#2]
It seems that the scale factors of bands `SR_B1` to `SR_B7` from the `LANDSAT/LC08/C02/T1_L2` collection are incorrect.

```
var spectral = require('users/dmlmont/spectral:spectral');
print(spectral.scaleParameters['LANDSAT/LC08/C02/T1_L2']);
```

<img width="205" alt="Captura de Tela 2021-09-03 às 22 38 26" src="https://user-images.githubusercontent.com/81490164/132078246-3ca7db1f-f715-4178-bd8c-92cf3c8e7411.png">

**Comment by davemlz** [comment]
Thank you for pointing it out, @iagomoliv! I have updated the whole list of scale and offset parameters :)

PD: The Collection 2 of Landsat 8 also has an offset value, so remember to offset the image you are using :)

```javascript
var spectral = require('users/dmlmont/spectral:spectral');
var dataset = 'LANDSAT/LC08/C02/T1_L2'
var L8 = ee.ImageColection(dataset).first()
var L8_scale = spectral.scale(L8,dataset)
var L8_scale_offset = spectral.offset(L8_scale,dataset)
```
