### ISSUE TITLE
Exporting indices as 16 bit shorts

### ISSUE THREAD

**Issue by lucas-johnson** [awesome-spectral-indices/spectral#6]
Hi David – thanks for an awesome library! This is already saving me so much work looking up / hardcoding index formulas...

I'm exporting all of my images as 16 bit integers, and in for many indices I'm seeing discrete integer values and some that are simply binary... This is telling me I need to multiply by 1000 (or similar) in some cases. This is what I do with NDVI that I compute on my own. 

So I'm wondering if this a common issue, and if there is someway to tell which indices need to be scaled beyond just a call to `spectral.computeIndex`? Perhaps the problem is simply that I'm casting everything to 16 bit integers so I'm on my own... 

Thank you!

**Comment by davemlz** [comment]
Hi @lucas-johnson!

Thank you!

Yes. If you want to save them as 16-bit integers you have to multiply them by 10000. Since most indices are floating points going from -1 to 1, when you cast them you will get just -1, 0, or 1.

If size is not a problem, you could export them as floating points :)

Cheers,

Dave

**Comment by davemlz** [comment]
Also. Please note that some indices may get quite large (like CIG or CIRE). If you multiply them by 10000 and cast them as 16-bit you may lose some data.

**Comment by lucas-johnson** [comment]
@davemlz Thank you for the quick response!

That makes sense.  I think it would nice to include `range` or similar as a field in the json blob. So then somebody (like me) could use that to decide whether or not to multiply by 10,000. 

Thanks again!

**Comment by davemlz** [comment]
That is a good idea! I will try to add it as a new attribute!

Thank you!

I'm closing this issue now.
